spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gourav-Jagga/smarthealth-config-repo.git
          searchPaths: '{application}'
          clone-on-start: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8888
